services:
  db:
    image: postgres:latest
    restart: always
    container_name: db-puma
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    
volumes:
  postgres-data:
