services:
  db:
    image: postgres:latest
    restart: always
    container_name: db-puma
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env

  test:
    image: postgres:latest
    restart: always
    container_name: db-test
    ports:
      - 5433:5432
    env_file:
      - ../.env

volumes:
  postgres-data:
